---
name: Egg-Plugin-Authen-Captcha
version: 0.01
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: Plugin for Authen::Captcha.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Authen::Captcha: 1.02
  Class::Data::Inheritable: 0.06
  Egg::Release: 2.24
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::Authen::Captcha:
    file: lib/Egg/Plugin/Authen/Captcha.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
